# Build settings

markdown: kramdown
permalink: pretty

baseurl: "/ysl-blog"
url: "http://persephonepunch.github.io"
tagline: "blog done in Jekyll/Liquid"

port: 8000

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
