#-------------------------------
# General Site Settings

title: YSL150
description: Designer | Developer
email: yoonsunlee150@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/117295259863091022096/posts'
  rel-publisher: 'https://plus.google.com/u/0/117295259863091022096'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Yoonsun** is a creator.
  She started out as a print designer who went to RISD.
  She got the technology bug. Along the way she learned how things work.
  You can find her more of her work here [ysl150.com](http://www.ysl150.com/){:target="_blank"}.


skills:
- {name: Design, value: '10'}
- {name: UX, value: '10'}
- {name: Discovery, value: '10'}
- {name: Persona, value: '10'}
- {name: Proof of Concept, value: '10'}
- {name: Product Development, value: '10'}
- {name: PR and Launch Programs, value: '10'}
- {name: Interactive Education/Intranets, value: '10'}

#-------------------------------
# Work Section

projects:
- {name: HBO GO, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Cinemax GO, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Affiliate/IOT POC, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Forbes, folder: 'proj-5', file: 'work/proj-5.html'}





#-------------------------------
# Clients Section

clients:
- {avatar: 'face-carley.jpg',
  name: 'Carley Roney',
  title: 'Co-Founder of the knot.com',
  quote: '<p><strong>She is very creative, knows her stuff</strong> and always knows what is going on on the cutting edge of digital design. She also is great at the basics -- brilliant design, great typography, nice usability, etc. She has done online, brand work, as well as print design for me over the years. She is also great for my staff to work with becuase she is very nice to everyone, no matter what their place on the totem pole. She is encouraging, nurturing, teaches well, etc. And finally she is a great person to have around, warm, friendly, good natured and always has a positive outlook on life.</p>',
 }
- {avatar: 'face-maynard.jpg',
  name: 'Maynard Kay',
  title: 'Creative Director, HBO',
  quote: '<p><strong>A great mentor and a great friend,</strong> she is incredibly creative and passionate about her work. Her ability to remain ahead of the curve with tech and design trends make her an invaluable asset for any team.</p>',
 }
  
- {avatar: 'face-fayette.jpg',
  name: 'Fayette Hickox',
  title: 'Creative Director, Clinique',
  quote: '<p><strong>Yoonsun is a blazing talent,                 </strong>  <br> utterly civilized and a total delight.</p>',
 }
  
  




#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/everdenepublic'}
- {icon: 'behance', link: 'https://www.behance.net/ysl150'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yoonsunlee'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
